### ISSUE TITLE
Missing Play And Search Button

### ISSUE THREAD

**Issue by AndreaLonghitano** [phandd/spotless#12]
Search and play buttons miss.

**Comment by phandd** [comment]
Hi, due to Google's policy of single responsibility. I had to remove the search and play feature. You can re-enable it by editing the code

**Comment by AndreaLonghitano** [comment]
> Hi, due to Google's policy of single responsibility. I had to remove the search and play feature. You can re-enable it by editing the code

The components are already available? I cannot find it inside the directory.

**Comment by phandd** [comment]
Hi, I re-enabled search and play, you should be able to use it now
