### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by pirate** [phandd/spotless#9]
How is this codebase licensed, is it MIT/BSD/Apache/etc?

Can we fork this codebase to develop a different extension? We won't be competing with this one (i.e. it won't be a Spotify music controller extension, we want to build an extension for a completely different product to scrape music off pages the user is looking at).

**Comment by panurar** [comment]
> How is this codebase licensed, is it MIT/BSD/Apache/etc?
> 
> Can we fork this codebase to develop a different extension? We won't be competing with this one (i.e. it won't be a Spotify music controller extension, we want to build an extension for a completely different product to scrape music off pages the user is looking at).

**Comment by panurar** [comment]
Sorry I need to study for help family and people.

**Comment by panurar** [comment]
> `[Panurat](http://www.panurat.com) @panurar @` #8 
![Uploading  #line_54405199475911.jpg…]()
Hello

**Comment by phandd** [comment]
Hi, I have added the MIT license. Enjoy!
